services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/web.conf
      - ./src/views:/usr/share/nginx/html
    ports:
      - "3000:3000"
    depends_on:
      - php_fpm


  php_fpm:
    image: php:7.4-fpm
    volumes:
      - ./src/views:/usr/share/nginx/html

  procedures: 
    image: node:lts
    command: npm install && npm run server

